services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=comic_reader
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio-access-key
      MINIO_SECRET_KEY: minio-secret-key
    volumes:
      - /data:/data
      - /config:/root/.minio
    command: server /data
  
