import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Providers } from "./providers";
// import { ThemeToggle } from "@/components/ui/themeToggle";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          `h-screen bg-background font-sans antialiased flex items-center justify-center transition-all`,
          inter.className
        )}
      >
        <Providers attribute="class" defaultTheme="system">
          {children}
        </Providers>
      </body>
    </html>
  );
}
